language: java

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - jdk_switcher use oraclejdk8
  - gradle build
  - gradle :DeepMill:clean :DeepMillServer:clean
  - jdk_switcher use oraclejdk7
  - gradle build

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true
